# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Testimony

# Model Form Field configuration
form: @/plugins/mja/testimonies/models/testimony/fields.yaml

# Model Class name
modelClass: Mja\Testimonies\Models\Testimony

# Default redirect location
defaultRedirect: mja/testimonies/testimonies

# Create page
create:
    title: Create Testimony
    redirect: mja/testimonies/testimonies/update/:id
    redirectClose: mja/testimonies/testimonies

# Update page
update:
    title: Edit Testimony
    redirect: mja/testimonies/testimonies
    redirectClose: mja/testimonies/testimonies
